### ISSUE TITLE
Issue with java completion.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1329]
Hello. I have built ycmd with 

~~~
cd ~/bin/
git clone git@github.com:ycm-core/ycmd.git ycmd-code
cd ycmd-code
ls
git submodule update --init --recursive
ls

# typescript is for tsserver. clang is for c-family completion.
# Installing gradle it installs jdk10-opendk
pacman -S clang cmake gcc-c++ make python3-devel typescript python3-dev gradle

# Compiling ycmd with all features. The --cs-completer, -go-completer are 
# flags to install the necessary tools.
python3 install.py --all
~~~

I get this error:

~~~
[tau@archlinux javaproject]$ vy src/main/java/hello/HelloWorld.java 
serving on http://localhost:2870
2019-09-26 19:35:38,262 - INFO - Received event notification
2019-09-26 19:35:38,262 - INFO - Adding buffer identifiers for file: /home/tau/tests/javaproject/src/main/java/hello/HelloWorld.java
2019-09-26 19:35:38,269 - INFO - Looking for jdt.ls
2019-09-26 19:35:38,271 - INFO - extension directory does not exist: /home/tau/bin/ycmd-code/third_party/eclipse.jdt.ls/extensions
Traceback (most recent call last):
  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/tau/bin/ycmd-code/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/home/tau/bin/ycmd-code/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/home/tau/bin/ycmd-code/ycmd/handlers.py", line 67, in EventNotification
    event_handler )( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/language_server/language_server_completer.py", line 1187, in OnFileReadyToParse
    self._StartAndInitializeServer( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/language_server/language_server_completer.py", line 1173, in _StartAndInitializeServer
    extra_conf_dir = self._GetSettingsFromExtraConf( request_data )
  File "/home/tau/bin/ycmd-code/ycmd/completers/language_server/language_server_completer.py", line 1153, in _GetSettingsFromExtraConf
    module = extra_conf_store.ModuleForSourceFile( request_data[ 'filepath' ] )
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 62, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 73, in ModuleFileForSourceFile
    if Load( module_file ):
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 158, in Load
    if not force and not _ShouldLoad( module_file, is_global ):
  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 141, in _ShouldLoad
    raise UnknownExtraConf( module_file )
ycmd.responses.UnknownExtraConf: Found /home/tau/.ycm_extra_conf.py. Load? 

(Question can be turned off with options, see YCM docs)
FileReadyToParse JSON:
 {'exception': {'extra_conf_file': '/home/tau/.ycm_extra_conf.py', 'TYPE': 'UnknownExtraConf'}, 'message': 'Found /home/tau/.ycm_extra_conf.py. Load? \n\n(Question can be turned off with options, see YCM docs)', 'traceback': 'Traceback (most recent call last):\n  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 862, in _handle\n    return route.call(**args)\n  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 1740, in wrapper\n    rv = callback(*a, **ka)\n  File "/home/tau/bin/ycmd-code/ycmd/watchdog_plugin.py", line 104, in wrapper\n    return callback( *args, **kwargs )\n  File "/home/tau/bin/ycmd-code/ycmd/hmac_plugin.py", line 68, in wrapper\n    body = callback( *args, **kwargs )\n  File "/home/tau/bin/ycmd-code/ycmd/handlers.py", line 67, in EventNotification\n    event_handler )( request_data )\n  File "/home/tau/bin/ycmd-code/ycmd/completers/language_server/language_server_completer.py", line 1187, in OnFileReadyToParse\n    self._StartAndInitializeServer( request_data )\n  File "/home/tau/bin/ycmd-code/ycmd/completers/language_server/language_server_completer.py", line 1173, in _StartAndInitializeServer\n    extra_conf_dir = self._GetSettingsFromExtraConf( request_data )\n  File "/home/tau/bin/ycmd-code/ycmd/completers/language_server/language_server_completer.py", line 1153, in _GetSettingsFromExtraConf\n    module = extra_conf_store.ModuleForSourceFile( request_data[ \'filepath\' ] )\n  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 62, in ModuleForSourceFile\n    return Load( ModuleFileForSourceFile( filename ) )\n  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 73, in ModuleFileForSourceFile\n    if Load( module_file ):\n  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 158, in Load\n    if not force and not _ShouldLoad( module_file, is_global ):\n  File "/home/tau/bin/ycmd-code/ycmd/extra_conf_store.py", line 141, in _ShouldLoad\n    raise UnknownExtraConf( module_file )\nycmd.responses.UnknownExtraConf: Found /home/tau/.ycm_extra_conf.py. Load? \n\n(Question can be turned off with options, see YCM docs)\n'}
2019-09-26 19:35:38,392 - INFO - Received extra conf load request
File to load: /home/tau/.ycm_extra_conf.py
Load conf response: True
Loading extra conf...
~~~

Using https://github.com/vyapp/vy/blob/development/vyapp/plugins/ycmd/client.py

**Comment by bstaletic** [comment]
Like I mentioned in https://github.com/ycm-core/ycmd/issues/1325#issuecomment-533795168, extra conf file can be used to configure jdt.ls, so ycmd tries to find an extra conf file to allow user configuration. This is working as intended.

**Comment by iogf** [comment]
This is my extra conf.

~~~python
# This file is NOT licensed under the GPLv3, which is the license for the rest
# of YouCompleteMe.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

from distutils.sysconfig import get_python_inc
import platform
import os.path as p
import subprocess
import ycm_core

DIR_OF_THIS_SCRIPT = p.abspath( p.dirname( __file__ ) )
DIR_OF_THIRD_PARTY = p.join( DIR_OF_THIS_SCRIPT, 'third_party' )
SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]

# These are the compilation flags that will be used in case there's no
# compilation database set (by default, one is not set).
# CHANGE THIS LIST OF FLAGS. YES, THIS IS THE DROID YOU HAVE BEEN LOOKING FOR.
flags = [
'-Wall',
'-Wextra',
'-Werror',
'-Wno-long-long',
'-Wno-variadic-macros',
'-fexceptions',
'-DNDEBUG',
# You 100% do NOT need -DUSE_CLANG_COMPLETER and/or -DYCM_EXPORT in your flags;
# only the YCM source code needs it.
'-DUSE_CLANG_COMPLETER',
'-DYCM_EXPORT=',
# THIS IS IMPORTANT! Without the '-x' flag, Clang won't know which language to
# use when compiling headers. So it will guess. Badly. So C++ headers will be
# compiled as C headers. You don't want that so ALWAYS specify the '-x' flag.
# For a C project, you would set this to 'c' instead of 'c++'.
'-x',
'c++',
'-isystem',
'cpp/pybind11',
'-isystem',
'cpp/whereami',
'-isystem',
'cpp/BoostParts',
'-isystem',
get_python_inc(),
'-isystem',
'cpp/llvm/include',
'-isystem',
'cpp/llvm/tools/clang/include',
'-I',
'cpp/ycm',
'-I',
'cpp/ycm/ClangCompleter',
'-isystem',
'cpp/ycm/tests/gmock/gtest',
'-isystem',
'cpp/ycm/tests/gmock/gtest/include',
'-isystem',
'cpp/ycm/tests/gmock',
'-isystem',
'cpp/ycm/tests/gmock/include',
'-isystem',
'cpp/ycm/benchmarks/benchmark/include',
]

# Clang automatically sets the '-std=' flag to 'c++14' for MSVC 2015 or later,
# which is required for compiling the standard library, and to 'c++11' for older
# versions.
if platform.system() != 'Windows':
  flags.append( '-std=c++11' )


# Set this to the absolute path to the folder (NOT the file!) containing the
# compile_commands.json file to use that instead of 'flags'. See here for
# more details: http://clang.llvm.org/docs/JSONCompilationDatabase.html
#
# You can get CMake to generate this file for you by adding:
#   set( CMAKE_EXPORT_COMPILE_COMMANDS 1 )
# to your CMakeLists.txt file.
#
# Most projects will NOT need to set this to anything; you can just change the
# 'flags' list of compilation flags. Notice that YCM itself uses that approach.
compilation_database_folder = ''

if p.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None


def IsHeaderFile( filename ):
  extension = p.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def FindCorrespondingSourceFile( filename ):
  if IsHeaderFile( filename ):
    basename = p.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if p.exists( replacement_file ):
        return replacement_file
  return filename


def PathToPythonUsedDuringBuild():
  try:
    filepath = p.join( DIR_OF_THIS_SCRIPT, 'PYTHON_USED_DURING_BUILDING' )
    with open( filepath ) as f:
      return f.read().strip()
  # We need to check for IOError for Python 2 and OSError for Python 3.
  except ( IOError, OSError ):
    return None


def Settings( **kwargs ):
  language = kwargs[ 'language' ]

  if language == 'cfamily':
    # If the file is a header, try to find the corresponding source file and
    # retrieve its flags from the compilation database if using one. This is
    # necessary since compilation databases don't have entries for header files.
    # In addition, use this source file as the translation unit. This makes it
    # possible to jump from a declaration in the header file to its definition
    # in the corresponding source file.
    filename = FindCorrespondingSourceFile( kwargs[ 'filename' ] )

    if not database:
      return {
        'flags': flags,
        'include_paths_relative_to_dir': DIR_OF_THIS_SCRIPT,
        'override_filename': filename
      }

    compilation_info = database.GetCompilationInfoForFile( filename )
    if not compilation_info.compiler_flags_:
      return {}

    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object.
    final_flags = list( compilation_info.compiler_flags_ )

    # NOTE: This is just for YouCompleteMe; it's highly likely that your project
    # does NOT need to remove the stdlib flag. DO NOT USE THIS IN YOUR
    # ycm_extra_conf IF YOU'RE NOT 100% SURE YOU NEED IT.
    try:
      final_flags.remove( '-stdlib=libc++' )
    except ValueError:
      pass

    return {
      'flags': final_flags,
      'include_paths_relative_to_dir': compilation_info.compiler_working_dir_,
      'override_filename': filename
    }

  if language == 'python':
    return {
      'interpreter_path': PathToPythonUsedDuringBuild()
    }

  return {}


def GetStandardLibraryIndexInSysPath( sys_path ):
  for index, path in enumerate( sys_path ):
    if p.isfile( p.join( path, 'os.py' ) ):
      return index
  raise RuntimeError( 'Could not find standard library path in Python path.' )


def PythonSysPath( **kwargs ):
  sys_path = kwargs[ 'sys_path' ]

  interpreter_path = kwargs[ 'interpreter_path' ]
  major_version = subprocess.check_output( [
    interpreter_path, '-c', 'import sys; print( sys.version_info[ 0 ] )' ]
  ).rstrip().decode( 'utf8' )

  sys_path.insert( GetStandardLibraryIndexInSysPath( sys_path ) + 1,
                   p.join( DIR_OF_THIRD_PARTY, 'python-future', 'src' ) )
  sys_path[ 0:0 ] = [ p.join( DIR_OF_THIS_SCRIPT ),
                      p.join( DIR_OF_THIRD_PARTY, 'bottle' ),
                      p.join( DIR_OF_THIRD_PARTY, 'cregex',
                              'regex_{}'.format( major_version ) ),
                      p.join( DIR_OF_THIRD_PARTY, 'frozendict' ),
                      p.join( DIR_OF_THIRD_PARTY, 'jedi_deps', 'jedi' ),
                      p.join( DIR_OF_THIRD_PARTY, 'jedi_deps', 'numpydoc' ),
                      p.join( DIR_OF_THIRD_PARTY, 'jedi_deps', 'parso' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps', 'requests' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'urllib3',
                                                  'src' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'chardet' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'certifi' ),
                      p.join( DIR_OF_THIRD_PARTY, 'requests_deps',
                                                  'idna' ),
                      p.join( DIR_OF_THIRD_PARTY, 'waitress' ) ]

  return sys_path
~~~

**Comment by bstaletic** [comment]
But `/home/tau/.ycm_extra_conf.py` is "unknown" to ycmd. Please re-read carefully the comment I linked above (https://github.com/ycm-core/ycmd/issues/1325#issuecomment-533795168). I explained in detail how extra confs work.

**Comment by puremourning** [comment]
You need to either load or whitelist the extra conf file.

**Comment by iogf** [comment]
That file is being loaded by vy. The issue consists of this:

~~~
tau@archlinux javaproject]$ vy src/main/java/hello/HelloWorld.java 
serving on http://localhost:9601
2019-09-27 14:54:50,044 - INFO - Received event notification
2019-09-27 14:54:50,045 - INFO - Adding buffer identifiers for file: /home/tau/tests/javaproject/src/main/java/hello/HelloWorld.java
2019-09-27 14:54:50,053 - INFO - Looking for jdt.ls
2019-09-27 14:54:50,055 - INFO - extension directory does not exist: /home/tau/bin/ycmd-code/third_party/eclipse.jdt.ls/extensions
Traceback (most recent call last):
~~~

It seems even after building it with --all it doesn't contain the extensions directory for jdt.ls.

I searched and in fact it doesn't exist in the ycmd code. Which kind of settings should i use in .ycm_extra_conf to get it working with java then?

**Comment by bstaletic** [comment]
That directory doesn't exist for me either, but java still works. However, jdt.ls takes an eternity to start. Jdt.ls repeatedly sends `window/logMessage` until it sends `Started`. You can see this in the debug info response and the vim client also constantly gets the status in the commandline. So the obvious question is "Have you allowed jdt.ls enough time to start?"

**Comment by puremourning** [comment]
The extension directory doesn’t need to exist. 

What’s the actual trace back? And debug info output?

**Comment by iogf** [comment]
I'm trying to get debug_info working. Check this https://github.com/ycm-core/ycmd/issues/1330

**Comment by puremourning** [comment]
If jdt.ls isn't starting, check:

* the ycmd stderr log 
* the jdt.ls log (the path to it is in the debug info response)

Make sure to set the "server_keep_log_files" option to 1 in your settings file.

**Comment by iogf** [comment]
This is the debug_info.

~~~
2019-09-28 13:01:04,457 - INFO - Received debug info request
Ycmd - debug_info Event Response JSON:
 {'python': {'executable': '/usr/bin/python', 'version': '3.7.4'}, 'clang': {'has_support': True, 'version': 'clang version 8.0.0 (tags/RELEASE_800/final)'}, 'extra_conf': {'path': '/home/tau/.ycm_extra_conf.py', 'is_loaded': True}, 'completer': {'name': 'Java', 'servers': [{'name': 'jdt.ls Java Language Server', 'is_running': False, 'executable': '/home/tau/bin/ycmd-code/third_party/eclipse.jdt.ls/target/repository/plugins/org.eclipse.equinox.launcher_1.5.400.v20190515-0925.jar', 'address': None, 'port': None, 'pid': None, 'logfiles': [], 'extras': [{'key': 'Startup Status', 'value': 'Not started'}, {'key': 'Java Path', 'value': '/usr/bin/java'}, {'key': 'Extension Path', 'value': ['/home/tau/bin/ycmd-code/third_party/eclipse.jdt.ls/extensions']}, {'key': 'Server State', 'value': 'Dead'}, {'key': 'Project Directory', 'value': None}, {'key': 'Settings', 'value': '{\n  "bundles": []\n}'}]}], 'items': []}}

~~~

**Comment by bstaletic** [comment]
Like @puremourning said, we'll need logs. Please come to [gitter](https://gitter.im/Valloric/YouCompleteMe).
