### ISSUE TITLE
Weird exception on /debug_info.

### ISSUE THREAD

**Issue by iogf** [ycm-core/ycmd#1330]
I'm getting this exception when i send debug info.

~~~
2019-09-28 12:08:09,703 - INFO - Received event notification
Traceback (most recent call last):
  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/tau/bin/ycmd-code/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/home/tau/bin/ycmd-code/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/home/tau/bin/ycmd-code/ycmd/handlers.py", line 61, in EventNotification
    getattr( _server_state.GetGeneralCompleter(), event_handler )( request_data )
AttributeError: 'GeneralCompleterStore' object has no attribute 'Ondebug_info'
Ycmd - /debug_info status 500
Ycmd - debug_info Event Response JSON:
 {'exception': {'TYPE': 'AttributeError'}, 'message': "'GeneralCompleterStore' object has no attribute 'Ondebug_info'", 'traceback': 'Traceback (most recent call last):\n  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 862, in _handle\n    return route.call(**args)\n  File "/home/tau/bin/ycmd-code/third_party/bottle/bottle.py", line 1740, in wrapper\n    rv = callback(*a, **ka)\n  File "/home/tau/bin/ycmd-code/ycmd/watchdog_plugin.py", line 104, in wrapper\n    return callback( *args, **kwargs )\n  File "/home/tau/bin/ycmd-code/ycmd/hmac_plugin.py", line 68, in wrapper\n    body = callback( *args, **kwargs )\n  File "/home/tau/bin/ycmd-code/ycmd/handlers.py", line 61, in EventNotification\n    getattr( _server_state.GetGeneralCompleter(), event_handler )( request_data )\nAttributeError: \'GeneralCompleterStore\' object has no attribute \'Ondebug_info\'\n'}
~~~

**Comment by bstaletic** [comment]
`debug_info` isn't an event notification. It is a request to which you should expect a response.
https://ycm-core.github.io/ycmd/#path--debug_info

**Comment by puremourning** [comment]
When reporting an issue with the API, pease can you try and include the actual request and reply including parameters and payloads? You can either print these from your app or you can use something like Wireshark to snoop the http transport. It's impossible to debug api-like queries without seeing the exact API calls and responses being made.

Anyway, as Boris says it's probably that you should be just POST to /debug_info

TBH it's probably more efficient to jump on our Gitter channel than to post issues that represent help with using the API. The issue tracker is for bugs and feature requets, the Gitter channel is for help.

**Comment by iogf** [comment]
I'll hang on gitter. Thank you.
