### ISSUE TITLE
failed to go to definition of a dict variable in python.

### ISSUE THREAD

**Issue by apporc** [ycm-core/ycmd#1364]
Related logs:
```
Traceback (most recent call last):
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 102, in RunCompleterCommand
    request_data ) )
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/completers/completer.py", line 397, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/completers/python/python_completer.py", line 273, in <lambda>
    self._GoToDefinition( request_data ) ),
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/completers/python/python_completer.py", line 307, in _GoToDefinition
    return self._BuildGoToResponse( definitions )
  File "/home/apporc/.cache/dein/repos/github.com/Valloric/YouCompleteMe/third_party/ycmd/ycmd/completers/python/python_completer.py", line 292, in _BuildGoToResponse
    definition.column + 1 )
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

After a simple debug, If the variable is of type string, GoTo will jump to a builtin.pyi file, and if this variable is of type dict, it will report an error like above. It seems both are wrong.

For example:

```
# abc.py
import dxt


if __name__ == '__main__':
    print(dxt.xxx)
    print(dxt.yyy)
 
# dxt.py
xxx = {'abc': 'def'}
yyy = 'abc'
```

**Comment by puremourning** [comment]
As you are using YouCompleteMe, please raise on the YCM repo, completing the issue template./

**Comment by bstaletic** [comment]
This is a very tough issue. See #1359
