### ISSUE TITLE
Constant KeyError: '&filetype' using ycmd in emacs with emacs-ycmd and company-ycmd

### ISSUE THREAD

**Issue by josephemorgan91** [ycm-core/ycmd#1425]
Completions seem to be working perfectly, but I'm constantly getting an error message that is spamming the minibuffer. I'm on arch linux using ycmd that I pulled and built today, clang version 9.1 and emacs 26.3.

Stack trace is:

```
Traceback (most recent call last):
  File "/home/joe/make/ycmd/third_party/bottle/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/home/joe/make/ycmd/third_party/bottle/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/home/joe/make/ycmd/ycmd/watchdog_plugin.py", line 97, in wrapper
    return callback( *args, **kwargs )
  File "/home/joe/make/ycmd/ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/home/joe/make/ycmd/ycmd/handlers.py", line 63, in EventNotification
    response_data = getattr( _server_state.GetFiletypeCompleter( filetypes ),
  File "/home/joe/make/ycmd/ycmd/completers/cpp/clang_completer.py", line 364, in OnFileReadyToParse
    flags, filename = self._FlagsForRequest( request_data )
  File "/home/joe/make/ycmd/ycmd/completers/cpp/clang_completer.py", line 462, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/home/joe/make/ycmd/ycmd/completers/cpp/flags.py", line 131, in FlagsForFile
    results = self._GetFlagsFromExtraConfOrDatabase( filename, client_data )
  File "/home/joe/make/ycmd/ycmd/completers/cpp/flags.py", line 177, in _GetFlagsFromExtraConfOrDatabase
    return _CallExtraConfFlagsForFile( module, filename, client_data )
  File "/home/joe/make/ycmd/ycmd/completers/cpp/flags.py", line 267, in _CallExtraConfFlagsForFile
    results = module.FlagsForFile( filename, client_data = client_data )
  File "/home/joe/.dotfiles/utils/ycm_config.py", line 24, in FlagsForFile
    filetype = data['&filetype']
  File "/home/joe/make/ycmd/ycmd/utils.py", line 418, in __getitem__
    return copy.deepcopy( self._dict[ key ] )
KeyError: '&filetype'
```

My ycm_config.py is:

```
def FlagsForFile(filename, **kwargs):

  flags = [
    '-Wall',
    '-Wextra',
    '-Werror'
    '-pedantic',
    '-I',
    '.',
    '-isystem',
    '/usr/include',
    '-isystem',
    '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include',
    '-isystem',
    '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/5.1/include',
    '-isystem',
    '/usr/local/include',
    '-isystem',
    '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1',
  ]

  data = kwargs['client_data']
  filetype = data['&filetype']

  if filetype == 'c':
    flags += ['-xc']
  elif filetype == 'cpp':
    flags += ['-xc++']
    flags += ['-std=c++11']
  elif filetype == 'objc':
    flags += ['-ObjC']
  else:
    flags = []

  return {
    'flags':    flags,
    'do_cache': True
  }
```
Edited to fix formatting

**Comment by puremourning** [comment]
The error is in your extra conf file


filetype = data['&filetype']

Your client is not sending that key (which is likely vim-related anyway). Check your client configuration.

**Comment by josephemorgan91** [comment]
Thanks for the reply.

That makes a lot of sense, my ycm_global_conf.py has been taken directly from the one I use with Vim.

**Comment by puremourning** [comment]
I'll close this then :)
