### ISSUE TITLE
Can't get the TSServer example running

### ISSUE THREAD

**Issue by BorisKozo** [ycm-core/ycmd#1461]
Hi,

I am going to implement code completion for an internal editor we are using. Our code is JavaScript and all of our functionality is defined using ```.d.ts``` files (we don't actually have any TypeScript code). I am trying to see if I can use ycmd to get the same level of code completion as Visual Studio code which supports .js + .d.ts combination. 

Currently I am trying to run the provided example. I disabled all the calls except the JavaScript completion call. 
When the TSServer starts it throws the following error:

````
2020-08-05 14:09:19,114 - INFO - Using TypeScript completer with C:\projects\ycmd\third_party\tsserver\tsserver.cmd
2020-08-05 14:09:19,128 - INFO - TSServer log file: C:\Users\<my user>\AppData\Local\Temp\tsserver_d6psm6xk.log
2020-08-05 14:09:19,138 - INFO - TSServer started with PID 7308
2020-08-05 14:09:19,149 - INFO - Enabling TypeScript completion
2020-08-05 14:09:19,682 - INFO - Received typingsInstallerPid event from TSServer
Traceback (most recent call last):
  File "C:\projects\ycmd\third_party\bottle\bottle.py", line 868, in _handle
    return route.call(**args)
  File "C:\projects\ycmd\third_party\bottle\bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "C:\projects\ycmd\ycmd\watchdog_plugin.py", line 97, in wrapper
    return callback( *args, **kwargs )
  File "C:\projects\ycmd\ycmd\hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "C:\projects\ycmd\ycmd\handlers.py", line 63, in EventNotification
    response_data = getattr( _server_state.GetFiletypeCompleter( filetypes ),
  File "C:\projects\ycmd\ycmd\completers\typescript\typescript_completer.py", line 482, in OnFileReadyToParse
    diagnostics = self.GetDiagnosticsForCurrentFile( request_data )
  File "C:\projects\ycmd\ycmd\completers\typescript\typescript_completer.py", line 563, in GetDiagnosticsForCurrentFile
    ts_diagnostics = self.GetTsDiagnosticsForCurrentFile( request_data )
  File "C:\projects\ycmd\ycmd\completers\typescript\typescript_completer.py", line 498, in GetTsDiagnosticsForCurrentFile
    self._GetSemanticDiagnostics( filepath ),
  File "C:\projects\ycmd\ycmd\completers\typescript\typescript_completer.py", line 653, in _GetSemanticDiagnostics
    return self._SendRequest( 'semanticDiagnosticsSync', {
  File "C:\projects\ycmd\ycmd\completers\typescript\typescript_completer.py", line 339, in _SendRequest
    return deferred.result()
  File "C:\projects\ycmd\ycmd\completers\typescript\typescript_completer.py", line 70, in result
    raise RuntimeError( message[ 'message' ] )
RuntimeError: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:141525:23)
    at ProjectService.doEnsureDefaultProjectForFile (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:144924:131)
    at ProjectService.ensureDefaultProjectForFile (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:144919:75)
    at IOSession.Session.getFileAndProjectWorker (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:148815:87)
    at IOSession.Session.getFileAndProject (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:148798:29)
    at IOSession.Session.getDiagnosticsWorker (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:148479:31)
    at IOSession.Session.getSemanticDiagnosticsSync (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:148619:29)
    at Session.handlers.ts.createMapFromTemplate._a.<computed> (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:147955:61)
    at C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:149555:88
    at IOSession.Session.executeWithRequestId (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:149546:28)
    at IOSession.Session.executeCommand (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:149555:33)
    at IOSession.Session.onMessage (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:149579:35)
    at Interface.<anonymous> (C:\projects\ycmd\third_party\tsserver\node_modules\typescript\lib\tsserver.js:150895:27)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:329:10)
    at Interface._normalWrite (readline.js:474:12)
    at Socket.ondata (readline.js:186:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
````

To get to this part I had to load the provided ```.ycm_extra_conf.py``` file by calling _LoadExtraConfFile_ at the beginning of the _LanguageAgnosticIdentifierCompletion_ function:

````
def LanguageAgnosticIdentifierCompletion( server ):

  server.LoadExtraConfFile( PATH_TO_EXTRA_CONF )
````

I tried to investigate this error but all the related information is quite old and setting the ```TSS_LOG``` environment variable doesn't seem to do anything.

I have to add that the JavaScript completion is working in the example but I am looking to integrate it with the d.ts file and I assume that TSServer will be needed for it.

I am running this on Windows 10 with latest Python and TypeScript 3.9. All was installed as per the instructions with no special errors.

Any help getting this to work will be appreciated.

Thanks!

**Comment by puremourning** [comment]
> RuntimeError: Error processing request. No Project.

try creating a jsconfig.json ?

https://github.com/ycm-core/YouCompleteMe#javascript-and-typescript-semantic-completion

**Comment by BorisKozo** [comment]
Tried adding the file to the example directory but it didn't work.
Is there a specific place where it needs to be?

**Comment by puremourning** [comment]
Can you run ycmd with --log DEBUG

**Comment by BorisKozo** [comment]
It added no extra information except this line:
```2020-08-05 14:45:09,871 - DEBUG - Event name: FileReadyToParse```

**Comment by puremourning** [comment]
Do you have the tsserver log? 

The name of the log file is provided by the [debug_info](https://ycm-core.github.io/ycmd/#path--debug_info) request

**Comment by BorisKozo** [comment]
This file is not getting created.
Even if I set TSS_LOG environment variable and give it my own file name neither file is created.

**Comment by puremourning** [comment]
Can you send the whole debug_info request and response ?

BTW, it might be easier to have this discussion "in person" in our Gitter channel https://gitter.im/Valloric/ycmd

**Comment by BorisKozo** [comment]
Thanks! I will pop in after the meeting or tomorrow.
Thank you for the help so far.

**Comment by puremourning** [comment]
The 'javascript' in the example was intended to test a filetype which doesn't have native support. but we've supported javascript natively for quite a long time and the sample has not been updated.

You can fix it by sending th [BufferVisit]() event, which the typescript completer relies on

```
diff --git a/examples/example_client.py b/examples/example_client.py
index a9ab3246..ebaf822f 100755
--- a/examples/example_client.py
+++ b/examples/example_client.py
@@ -50,6 +50,7 @@ COMPLETER_COMMANDS_HANDLER = '/run_completer_command'
 EVENT_HANDLER = '/event_notification'
 EXTRA_CONF_HANDLER = '/load_extra_conf_file'
 RECEIVE_MESSAGES_HANDLER = '/receive_messages'
+DEBUG_INFO_HANDLER = '/debug_info'
 DIR_OF_THIS_SCRIPT = os.path.dirname( os.path.abspath( __file__ ) )
 PATH_TO_YCMD = os.path.join( DIR_OF_THIS_SCRIPT, '..', 'ycmd' )
 PATH_TO_EXTRA_CONF = os.path.join( DIR_OF_THIS_SCRIPT, '.ycm_extra_conf.py' )
@@ -77,6 +78,8 @@ class YcmdHandle( object ):
     prepared_options = DefaultSettings()
     hmac_secret = os.urandom( HMAC_SECRET_LENGTH )
     prepared_options[ 'hmac_secret' ] = str( b64encode( hmac_secret ), 'utf-8' )
+    prepared_options[ 'confirm_extra_conf' ] = 0
+    prepared_options[ 'server_keep_logfiles' ] = 1

     # The temp options file is deleted by ycmd during startup.
     with NamedTemporaryFile( mode = 'w+', delete = False ) as options_file:
@@ -86,6 +89,7 @@ class YcmdHandle( object ):
     ycmd_args = [ sys.executable,
                   PATH_TO_YCMD,
                   f'--port={server_port}',
+                  '--log=debug',
                   f'--options_file={options_file.name}',
                   f'--idle_suicide_seconds={SERVER_IDLE_SUICIDE_SECONDS}' ]

@@ -141,6 +145,11 @@ class YcmdHandle( object ):
     self.PostToHandlerAndLog( DEFINED_SUBCOMMANDS_HANDLER, request_json )


+  def SendDebugInfoRequest( self, filetype ):
+    request_json = BuildRequestData( filetype = filetype )
+    print( '==== Sending dbeug info request ====' )
+    self.PostToHandlerAndLog( DEBUG_INFO_HANDLER, request_json )
+
   def SendCodeCompletionRequest( self,
                                  test_filename,
                                  filetype,
@@ -392,6 +401,10 @@ def PythonSemanticCompletionResults( server ):
 def LanguageAgnosticIdentifierCompletion( server ):
   # We're using JavaScript here, but the language doesn't matter; the identifier
   # completion engine just extracts identifiers.
+  server.SendEventNotification( Event.BufferVisit,
+                                test_filename = 'some_javascript.js',
+                                filetype = 'javascript' )
+
   server.SendEventNotification( Event.FileReadyToParse,
                                 test_filename = 'some_javascript.js',
                                 filetype = 'javascript' )
@@ -401,6 +414,8 @@ def LanguageAgnosticIdentifierCompletion( server ):
                                     line_num = 21,
                                     column_num = 6 )

+  server.SendDebugInfoRequest( filetype = 'javascript' )
+

 def CppSemanticCompletionResults( server ):
   # TODO: document this better
@@ -490,18 +505,6 @@ def Main():
   server.WaitUntilReady()

   LanguageAgnosticIdentifierCompletion( server )
-  PythonSemanticCompletionResults( server )
-  CppSemanticCompletionResults( server )
-  CsharpSemanticCompletionResults( server )
-  JavaMessages( server )
-
-  # This will ask the server for a list of subcommands supported by a given
-  # language completer.
-  PythonGetSupportedCommands( server )
-
-  # GoTo is an example of a completer subcommand.
-  # Python and C# completers also support the GoTo subcommand.
-  CppGotoDeclaration( server )

   print( 'Shutting down server...' )
   server.Shutdown()
```

**Comment by BorisKozo** [comment]
Thanks! That solved the issue and I got it running correctly.
