### ISSUE TITLE
language_server_completer.py Error

### ISSUE THREAD

**Issue by OurEra** [ycm-core/ycmd#1491]
**I am on  ubuntu18.04, after install YCM the java jdt.ls Server is showing Dead**

_Error Message:_

```
2020-10-25 21:19:23,030 - INFO - Completion config: 50, detailing 0 candiates
2020-10-25 21:19:23,030 - INFO - Completion config: 50, detailing 0 candiates
2020-10-25 21:19:23,031 - INFO - Completion config: 50, detailing 0 candiates
2020-10-25 21:19:23,031 - INFO - Completion config: 50, detailing 0 candiates
2020-10-25 21:19:23,076 - INFO - Received ready request
2020-10-25 21:19:23,081 - INFO - Received signature help available request
2020-10-25 21:19:23,083 - INFO - Received event notification
2020-10-25 21:19:23,084 - INFO - Looking for jdt.ls
2020-10-25 21:19:23,084 - INFO - Received event notification
2020-10-25 21:19:23,085 - INFO - Adding buffer identifiers for file: /home/shiruiwei/OurEra/lan-tests/java-test/com/srw/javatest/TestByteBuffer.java
2020-10-25 21:19:23,086 - INFO - Completion config: 50, detailing 0 candiates
2020-10-25 21:19:23,087 - INFO - extension directory does not exist: /home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/extensions
2020-10-25 21:19:23,089 - INFO - Starting jdt.ls Language Server...
2020-10-25 21:19:23,089 - INFO - Starting jdt.ls: ['/usr/bin/java', '-Dfile.encoding=UTF-8', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.product', '-Dlog.level=ALL', '-jar', '/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/target/repository/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar', '-configuration', '/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/workspace/config_linux', '-data', '/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/workspace/temp/tmpwet8ssv3']
2020-10-25 21:19:23,092 - INFO - jdt.ls started with PID 8254
2020-10-25 21:19:23,187 - INFO - Received filetype completion available request
2020-10-25 21:19:25,267 - ERROR - Received invalid protocol data from server: b'An error has occurred. See the log file'
Traceback (most recent call last):
  File "/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 560, in _ReadHeaders
    key, value = utils.ToUnicode( line ).split( ':', 1 ) 
ValueError: not enough values to unpack (expected 2, got 1)
2020-10-25 21:19:25,268 - ERROR - The language server communication channel closed unexpectedly. Issue a RestartServer command to recover.
Traceback (most recent call last):
  File "/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 363, in run 
    self._ReadMessages()
  File "/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 482, in _ReadMessages
    data, read_bytes, headers = self._ReadHeaders( data )
  File "/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 560, in _ReadHeaders
    key, value = utils.ToUnicode( line ).split( ':', 1 ) 
ValueError: not enough values to unpack (expected 2, got 1)
```

_Debug Info:_

```
Printing YouCompleteMe debug information...
-- Resolve completions: Never
-- Client logfile: /tmp/ycm_w87cc70k.log
-- Server Python interpreter: /usr/bin/python3
-- Server Python version: 3.6.9
-- Server has Clang support compiled in: True
-- Clang version: clang version 10.0.0 (https://github.com/ycm-core/llvm 038587147cf2f97d1c3e677042f69560c65b5bea)
-- No extra configuration file found
-- Java completer debug information:
--   jdt.ls not running
--   jdt.ls executable: ['/usr/bin/java', '-Dfile.encoding=UTF-8', '-Declipse.application=org.eclipse.jdt.ls.core.id1', '-Dosgi.bundles.defaultStartLevel=4', '-Declipse.product=org.eclipse.jdt.ls.core.pro
duct', '-Dlog.level=ALL', '-jar', '/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/target/repository/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar',
 '-configuration', '/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/workspace/config_linux', '-data', '/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/thir
d_party/eclipse.jdt.ls/workspace/temp/tmptzbouzms']
--   jdt.ls logfiles:
--     /tmp/jdt_ls_stderre7ma6uiq.log
--     /home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/workspace/temp/tmptzbouzms/.metadata/.log
--   jdt.ls Server State: Dead
--   jdt.ls Project Directory: /home/shiruiwei/OurEra/lan-tests/java-test/com/srw/javatest
--   jdt.ls Settings: {
--   "bundles": []
-- }
--   jdt.ls Startup Status: Not started
--   jdt.ls Java Path: /usr/bin/java
--   jdt.ls Launcher Config.: /home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/workspace/config_linux
--   jdt.ls Workspace Path: /home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/workspace/temp/tmptzbouzms
--   jdt.ls Extension Path: ['/home/shiruiwei/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/eclipse.jdt.ls/extensions']
-- Server running at: http://127.0.0.1:36223
-- Server process ID: 5217
-- Server logfiles:
--   /tmp/ycmd_36223_stdout_7460v3rd.log
--   /tmp/ycmd_36223_stderr_12n4l60u.log

```

**Comment by puremourning** [comment]
Do you have java 11 in your path?

**Comment by OurEra** [comment]
> Do you have java 11 in your path?

After upgrade to java 11, it worked, thanks. May be the java 11 requirement should add to FAQ.

**Comment by bstaletic** [comment]
You do get a warning during installation: https://github.com/ycm-core/ycmd/blob/master/build.py#L982-L985

Also, you can configure the `java_binary_path`, if you don't want to change the default java globally.

If you still think the FAQ is needed, feel free to contribute.
