### ISSUE TITLE
ycmd server crashes when piping into vim or using process substituion

### ISSUE THREAD

**Issue by acx0** [ycm-core/ycmd#1525]
repro:
```
$ ls | vim -
# or
$ vim -d <(echo foo) <(echo bar)
```

vim `:messages` output:
```
The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). Unexpected exit code 1. Type ':YcmToggleLogs ycmd_52525_stderr_cfxdny1s.log' to check the logs.
```

`ycmd.*log` contents:
```
2021-01-13 17:56:17,393 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
2021-01-13 17:56:17,415 - INFO - Completion config: 50, detailing 0 candiates
2021-01-13 17:56:17,416 - INFO - Completion config: 50, detailing 0 candiates
2021-01-13 17:56:17,416 - INFO - Completion config: 50, detailing 0 candiates
2021-01-13 17:56:17,416 - INFO - Completion config: 50, detailing 0 candiates
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sam/etc/vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 193, in <module>
    Main()
  File "/home/sam/etc/vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 184, in Main
    CloseStdin()
  File "/home/sam/etc/vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 140, in CloseStdin
    sys.stdin.close()
AttributeError: 'NoneType' object has no attribute 'close'
2021-01-13 17:56:17,417 - DEBUG - Global extra conf not loaded or no function VimClose
2021-01-13 17:56:17,417 - DEBUG - Global extra conf not loaded or no function Shutdown
```

**Comment by bstaletic** [comment]
Does this patch work?

```diff
diff --git a/ycmd/__main__.py b/ycmd/__main__.py
index 2073f970..0daba886 100644
--- a/ycmd/__main__.py
+++ b/ycmd/__main__.py
@@ -152,7 +152,8 @@ def SetupOptions( options_file ):


 def CloseStdin():
-  sys.stdin.close()
+  if sys.stdin:
+    sys.stdin.close()
   os.close( 0 )


```

**Comment by acx0** [comment]
That was my first guess, but it seems to cascade into `wsgi_server.py` after applying that change:

```
2021-01-14 12:29:05,596 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
2021-01-14 12:29:05,611 - INFO - Completion config: 50, detailing 0 candiates
2021-01-14 12:29:05,611 - INFO - Completion config: 50, detailing 0 candiates
2021-01-14 12:29:05,611 - INFO - Completion config: 50, detailing 0 candiates
2021-01-14 12:29:05,611 - INFO - Completion config: 50, detailing 0 candiates
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/sam/etc/vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 194, in <module>
    Main()
  File "/home/sam/etc/vim/plugged/YouCompleteMe/python/ycm/../../third_party/ycmd/ycmd/__main__.py", line 190, in Main
    handlers.wsgi_server.Run()
  File "/home/sam/etc/vim/plugged/YouCompleteMe/third_party/ycmd/ycmd/wsgi_server.py", line 35, in Run
    print( f'serving on http://{ self.effective_host }:{self.effective_port}' )
OSError: [Errno 9] Bad file descriptor
2021-01-14 12:29:05,618 - DEBUG - Global extra conf not loaded or no function VimClose
2021-01-14 12:29:05,618 - DEBUG - Global extra conf not loaded or no function Shutdown
```

**Comment by bstaletic** [comment]
Hmmm... What if you just comment out the print statement?

I'd test, but I'm not at home right now.

**Comment by acx0** [comment]
Just tried wrapping it in a `try/except: pass` and it seems to fix it. I imagine it's worth logging the error in an actual fix but this seems to resolve the issue.

**Comment by puremourning** [comment]
I’m not sure changing ycmd is totally right. It’s odd that ycmd is being attached to vims stdin

**Comment by bstaletic** [comment]
It is odd. It seems as if standard stream redirections on the command line get propagated to subprocesses.

**Comment by puremourning** [comment]
That's not super surprising. We'd have to use subprocess.PIPE on the client side otherwise ? Haven't checked what we actually do, but I suspect that any change would break windows. it always does.

**Comment by puremourning** [comment]
That said, guarding against stdin being closed already in ycmd wouldn't be the end of the world.

**Comment by bstaletic** [comment]
> Haven't checked what we actually do, but I suspect that any change would break windows. it always does.

Sounds about right. YCM is doing this:

        self._server_popen = utils.SafePopen( args, stdin_windows = PIPE,
                                              stdout = PIPE, stderr = PIPE )

Which calls:

```python
# A wrapper for subprocess.Popen that fixes quirks on Windows.
def SafePopen( args, **kwargs ):
  if OnWindows():
    # We need this to start the server otherwise bad things happen.
    # See issue #637.
    if kwargs.get( 'stdin_windows' ) is subprocess.PIPE:
      kwargs[ 'stdin' ] = subprocess.PIPE
    # Do not create a console window
    kwargs[ 'creationflags' ] = CREATE_NO_WINDOW

  kwargs.pop( 'stdin_windows', None )
  return subprocess.Popen( args, **kwargs )
```

> That said, guarding against stdin being closed already in ycmd wouldn't be the end of the world.

Seems like this issue is also about stdout being already closed. Then we attempt to redirect it to a file, which only sets `sys.stdout` to the new file handle. Finally we call that one `print()` which fails with `OSError: Bad file descriptor`.

When doing `vim <(some shell command)` (or other examples from @acx0), only stderr keeps working.
