### ISSUE TITLE
Could not find a valid MSVC version

### ISSUE THREAD

**Issue by Hallo89** [ycm-core/ycmd#1665]
- OS: Windows 10
- Visual Studio Build Tools 2019 (MSVC) version: 16.11.20

Hi,

after updating YouCompleteMe and trying to compile it, it no longer detects my MSVC installation as valid and fails (detailed report below).
This seems to have originated in commit https://github.com/ycm-core/ycmd/commit/3e9564b67ba3cf8651705da3ee9ed194e408f450, because the script now looks for the MSVC version in the registry, where, for me, it is not found (see below). Rolling back to a commit prior of this one works fine.

Input:
```fish
py install.py --ts-completer
```
Output:
```bash
Traceback (most recent call last):
  File "C:\Users\Hallo89\.vim\plugged\YouCompleteMe\third_party\ycmd\build.py", line 1335, in <module>
    Main()
  File "C:\Users\Hallo89\.vim\plugged\YouCompleteMe\third_party\ycmd\build.py", line 1295, in Main
    args = ParseArguments()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Hallo89\.vim\plugged\YouCompleteMe\third_party\ycmd\build.py", line 556, in ParseArguments
    raise FileNotFoundError( "Could not find a valid MSVC version." )
FileNotFoundError: Could not find a valid MSVC version.
```

![image](https://user-images.githubusercontent.com/21200815/200197359-a2b548d8-188a-471e-8a9c-6ef0b95ef6a5.png)
Registry entry searched for `17.0`, `16.0`, `15.0`

**Comment by puremourning** [comment]
Does it work if you specify --msvc ?

**Comment by puremourning** [comment]
Also msvc 15 is not supported. 15 is required. 

https://github.com/ycm-core/ycmd#supported-compilers


https://github.com/ycm-core/YouCompleteMe#supported-compilers

**Comment by puremourning** [comment]
@jmarrec do you know why it does not detect the users vs build tools?

**Comment by Hallo89** [comment]
> Does it work if you specify --msvc ?

Indeed it does work (With the command `py install.py --ts-completer --msvc 16`)! Presumably because this bypasses the automatic MSVC version check implemented in the commit mentioned above.

> Also msvc 14 is not supported. 15 is required.

Yes, i just wanted to show that the registry entries which the `FindLatestMSVC()` function looks for are not present on my machine, despite having it installed. 14 is just a remnant of an old version.

**Comment by puremourning** [comment]
I don't know either. I don't windows enough to be too bothered about it though it's sad to have regressed.
