### ISSUE TITLE
Can't GoTo function definition in Rust

### ISSUE THREAD

**Issue by Manishearth** [ycm-core/ycmd#309]
Calling GoTo on the `load_url()` [here](https://github.com/servo/servo/blob/master/components/script/dom/htmlanchorelement.rs#L197) causes a runtime error, in both Sublime and Vim:

```
[Ycmd][Server] Traceback (most recent call last):
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
[Ycmd][Server]     return route.call(**args)
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
[Ycmd][Server]     rv = callback(*a, **ka)
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
[Ycmd][Server]     return callback( *args, **kwargs )
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
[Ycmd][Server]     body = callback( *args, **kwargs )
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 86, in RunCompleterCommand
[Ycmd][Server]     request_data ) )
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 277, in OnUserCommand
[Ycmd][Server]     return command( self, request_data, arguments[ 1: ] )
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 356, in <lambda>
[Ycmd][Server]     self._GoToDefinition( request_data ) ),
[Ycmd][Server]   File "/home/manishearth/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 375, in _GoToDefinition
[Ycmd][Server]     raise RuntimeError( 'Can\'t jump to definition.' )
[Ycmd][Server] RuntimeError: Can't jump to definition.
```

cc @jwilm

**Comment by jwilm** [comment]
@Manishearth could you please include the racerd stderr log when this happened?

**Comment by Manishearth** [comment]
It's coming up empty for me

**Comment by Manishearth** [comment]
I suspect this happens for any method that's not defined in the same file but is from the same crate. E.g it happens on https://github.com/servo/euclid/blob/master/src/matrix.rs#L75 as well (small crate which you can use to repro locally)

**Comment by jwilm** [comment]
I'm surprised the error log is empty. Now I have two things to look into heh. Thanks for the report and a small test case.

Not exactly related, but I think we should also include some debug info in the 500 response so looking in the racerd log isn't necessary.

**Comment by Manishearth** [comment]
Side note: When I do `tail-f (server error log)` (not the racerd error log), the error log doesn't update until I exit vim.

**Comment by thevulch** [comment]
*Arch Linux, Neovim*

I'm having this issue too, but with trying to `GoTo` on `gen_range()` in the "Guessing Game" official tutorial. The code:
```rust
extern crate rand;
use std::io;
use std::cmp::Ordering;
use rand::Rng;

fn main() {
    println!("Guess the number!");
    let secret_number = rand::thread_rng().gen_range(1, 101);
}
```
It works for the `gen()` function, which is weird:
```rust
...
    let secret_number = rand::thread_rng().gen();
}
```
Here's the relevant part of the server error log:
```
2016-05-22 19:01:32,115 - ERROR - 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 379, in _GoToDefinition
    return responses.BuildGoToResponse( definition[ 'file_path' ],
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 106, in wrapper
    return callback( *args, **kwargs )
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 80, in RunCompleterCommand
    request_data ) )
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 329, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 363, in <lambda>
    self._GoToDefinition( request_data ) ),
  File "/home/jadin/dotfiles/nvim/plugged/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/rust/rust_completer.py", line 384, in _GoToDefinition
    raise RuntimeError( 'Can\'t jump to definition.' )
RuntimeError: Can't jump to definition.
```
There's nothing in the racer error log, but I got a `204 No Content` in the racer stdout log.

What's even weirder is that the autocompletion suggests `gen` at the `.`:
```rust
...
    let secret_number = rand::thread_rng().
}
```
But, it doesn't suggest `gen_range`, which is in the same crate/file, just a couple functions below `gen`. Is racer somehow not parsing `gen_range`?

**Comment by thevulch** [comment]
Oh, shoot, turns out my problem is a racer issue: phildawes/racer#541

**Comment by theli-ua** [comment]
With RLS support merged in the original reported issue is still kinda valid, there is no 
```
[2019-06-14T18:15:38Z TRACE rls::server::io] reading: 212 bytes
[2019-06-14T18:15:38Z TRACE rls::server] Read message `{"id": "19", "jsonrpc": "2.0", "method": "textDocument/definition", "params": {"position": {"character": 22, "line": 670}, "textDocument": {"uri": "file:///tmp/servo/components/script/dom/htmlanchorelement.rs"}}}`
[2019-06-14T18:15:38Z TRACE rls::server] Parsed message `RawMessage { method: "textDocument/definition", id: Str("19"), params: Object({"position": Object({"character": Number(22), "line": Number(670)}), "textDocument": Object({"uri": String("file:///tmp/servo/components/script/dom/htmlanchorelement.rs")})}) }`
[2019-06-14T18:15:38Z TRACE rls::server] Handling `textDocument/definition`
[2019-06-14T18:15:38Z TRACE rls::actions] convert_pos_to_span: "/tmp/servo/components/script/dom/htmlanchorelement.rs" Position { line: 670, character: 22 }
[2019-06-14T18:15:38Z TRACE rls::actions] line: `        target_window.load_url(url, replace, false, referrer, referrer_policy);
`
[2019-06-14T18:15:38Z TRACE rls::actions] start: 22, end: 30
[2019-06-14T18:15:38Z TRACE rls::actions::requests] goto_def (Racer): []
[2019-06-14T18:15:38Z TRACE rls::server::io] response: "Content-Length: 39\r\n\r\n{\"jsonrpc\":\"2.0\",\"id\":\"19\",\"result\":[]}"
```

```
2019-06-14 18:15:38,006 - DEBUG - TX: Sending message: b'Content-Length: 212\r\n\r\n{"id": "19", "jsonrpc": "2.0", "method": "textDocument/definition", "params": {"position": {"character": 22, "line": 670}, "textDocument": {"uri": "file:///tmp/servo/components/script/dom/htmlanchorelement.rs"}}}'
2019-06-14 18:15:38,016 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":"19","result":[]}'
Traceback (most recent call last):
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/watchdog_plugin.py", line 104, in wrapper
    return callback( *args, **kwargs )
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/hmac_plugin.py", line 68, in wrapper
    body = callback( *args, **kwargs )
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/handlers.py", line 82, in RunCompleterCommand
    request_data ) )
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/completer.py", line 350, in OnUserCommand
    return command( self, request_data, arguments[ 1: ] )
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 54, in <lambda>
    lambda self, request_data, args: self.GoTo( request_data, [ 'Definition' ] )
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1671, in GoTo
    result = self._GoToRequest( request_data, handlers[ 0 ] )
  File "/local/home/romanton/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/completers/language_server/language_server_completer.py", line 1654, in _GoToRequest
    raise RuntimeError( 'Cannot jump to location' )
RuntimeError: Cannot jump to location
```

However this isn't a ycmd issue either way.

**Comment by puremourning** [comment]
Agreed, if the server doesn't tell us, we can't jump.
