### ISSUE TITLE
How to request that the "obvious" extra-conf is loaded during file-ready?

### ISSUE THREAD

**Issue by abingham** [ycm-core/ycmd#32]
I noticed that `OnFileReadyToParse()` will look for an extra-conf file when one hasn't been configured. Is there any way that I can request that it be loaded? I'm imagining a flag in the request that says "if there's no config loaded, and if you find one that looks like it matches, load it."

Or perhaps better would be a separate explicit request to load the auto-detected extra-conf, something I could call before sending file-ready. 

My thinking is that, if ycmd is already doing these kinds of searches for extra-conf files, then it would be a waste to reimplement it client code...I should just reuse what ycmd's got.

FWIW, here's the traceback that led me to this question:

```
2014-09-04 07:50:19,558 - INFO - Received event notification
2014-09-04 07:50:19,558 - DEBUG - Event name: FileReadyToParse
2014-09-04 07:50:19,558 - INFO - Adding buffer identifiers for file: /Users/sixtynorth/projects/boost_python_exception/src/boost_python_exception/format_exception.cpp
Traceback (most recent call last):
  File "/Users/sixtynorth/projects/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/Users/sixtynorth/projects/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/hmac_plugin.py", line 54, in wrapper
    body = callback( *args, **kwargs )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/handlers.py", line 70, in EventNotification
    event_handler )( request_data )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 199, in OnFileReadyToParse
    flags = self._FlagsForRequest( request_data )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 261, in _FlagsForRequest
    return self._flags.FlagsForFile( filename, client_data = client_data )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/completers/cpp/flags.py", line 49, in FlagsForFile
    module = extra_conf_store.ModuleForSourceFile( filename )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/extra_conf_store.py", line 48, in ModuleForSourceFile
    return Load( ModuleFileForSourceFile( filename ) )
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/extra_conf_store.py", line 59, in ModuleFileForSourceFile
    if Load( module_file ):
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/extra_conf_store.py", line 134, in Load
    if not _ShouldLoad( module_file ):
  File "/Users/sixtynorth/projects/ycmd/ycmd/../ycmd/extra_conf_store.py", line 117, in _ShouldLoad
    raise UnknownExtraConf( module_file )
UnknownExtraConf: Found /Users/sixtynorth/projects/boost_python_exception/.ycm_extra_conf.py. Load? 
```

**Comment by puremourning** [comment]
YCMD api docs have covered this for some time.
